### ISSUE TITLE
✅ add : 페이지 레이아웃 구현

### ISSUE THREAD

**Issue by kangeunbidesign** [DeveloperAcademy-POSTECH/MC3-Team13-Inception#1]
## 💡 Issue

메인화면 레이아웃을 구현합니다.

## 📝  todo
- [x] AlarmCalculatorViewController 만들기
- [x] AlarmCalculatorViewController에서 NavigaitonTitle 만들기
- [x] AlarmCalculatorViewController에서 UITableView 구현하기
- [x] AlarmCalculatorViewController에서 UISegementedControl 구현하기
