### ISSUE TITLE
✅ add : 알람 목록 셀 UI 구성

### ISSUE THREAD

**Issue by chaneeii** [DeveloperAcademy-POSTECH/MC3-Team13-Inception#12]
## 💡 Issue
알람 목록 테이블의 셀 UI 를 구성합니다.

## 📝  todo
- [x] XIB / NIB 학습 
- [x] 알람 목록 테이블 셀 UI 구성
- [x] selected 상태에 따른 컨텐츠 컬러 변경

<p align="left">
  <img width="200" alt="알람목록테이블셀" src="https://user-images.githubusercontent.com/63157395/179420022-d5cbe9de-4788-4fa7-914f-87caf4b1fe2f.png">
</p>
