### ISSUE TITLE
✨ feat : 수면만족도화면 UI 구성

### ISSUE THREAD

**Issue by chaneeii** [DeveloperAcademy-POSTECH/MC3-Team13-Inception#2]
## 💡 Issue
수면 만족도 평가 화면 UI 작업

## 📝  todo
SleepSatisfactionViewController 생성 및 아래 항목 작업
- [x] Emoji 버튼 UI 작업
- [x] 저장하기 버튼 UI 작업
- [x] Emoji 버튼 선택 여부에 따른 저장하기 버튼 disable/enable 작업
- [x] 건너뛰기 / 페이지 닫기  UI 작업

Extension 추가
- [x] UIView : addsubview 
- [x] UIStackView : addArrangedSubview
- [x] UIButton : text에 underline 가능하도록 extension 추가

<p align="left">
  <img width="200" alt="2 0 Alarm Copy 21" src="https://user-images.githubusercontent.com/63157395/179346890-2c42876e-0ee9-43a5-b2ed-908488e3f780.png">
  <img width="200" alt="2 0 Alarm Copy 20" src="https://user-images.githubusercontent.com/63157395/179346892-7fe19b7a-2fd9-44e9-a262-c916ee78c30b.png">
</p>

##  👀 References
- https://yagom.net/forums/topic/disabled-uibutton%EC%9D%84-enable-%ED%95%98%EB%8A%94%EB%B2%95%EC%9D%84-%EC%95%8C%EB%A0%A4%EC%A3%BC%EC%84%B8%EC%9A%94/
- [UI컨트롤의 활성화여부를 동적으로 결정하는 법 – Cocoa, Swift](https://soooprmx.com/ui%EC%BB%A8%ED%8A%B8%EB%A1%A4%EC%9D%98-%ED%99%9C%EC%84%B1%ED%99%94%EC%97%AC%EB%B6%80%EB%A5%BC-%EB%8F%99%EC%A0%81%EC%9C%BC%EB%A1%9C-%EA%B2%B0%EC%A0%95%ED%95%98%EB%8A%94-%EB%B2%95-cocoa-swift/)
