### ISSUE TITLE
✨ feat : Core Data 사용해서 저장 구현

### ISSUE THREAD

**Issue by jinccc97** [DeveloperAcademy-POSTECH/MC3-Team13-Inception#21]
## 💡 Issue
Core Data 를 도입합니다.
저장된 알람 목록, 수면 기록을 저장합니다.

## 📝  todo
- [x] CoreData Manager 기반 세팅
- [x] 수면 기록 모델 생성
- [x] 수면 기록 저장 (CRU_)
- [x] 알림 목록 모델 생성
- [x] 알림 저장 및 삭제 (CRUD)
