### ISSUE TITLE
🐛 fix : AlarmListCell UI 수정

### ISSUE THREAD

**Issue by chaneeii** [DeveloperAcademy-POSTECH/MC3-Team13-Inception#35]
## 💡 Issue
- AlarmListCell UI 수정
   - 현재
     - 테이블에서 선택된 셀이 활성화색을 띄도록 구성됨
     - 기상/취침 시간이 양사이드에 constraints 가 설정되어있음 (빨강)
   - 변경 
     - 현재알람만 셀이 활성화색을 띄도록 변경
     - 기상/취침 constraints 를 가운데로 옮겨서 디바이스가 커지더라도 사이가 벌어지지 않게 할예정 (초록)

![스크린샷 2022-07-25 오후 10 54 09](https://user-images.githubusercontent.com/63157395/180794512-7c5d0423-ab9c-4ee2-934b-dfc2002348e4.png)
<img width="200" src="https://user-images.githubusercontent.com/63157395/180793418-bcf5f1c4-4277-4c05-8c7c-3c8fdbb6cb45.png" >

## 📝  todo
- [x] Cell Constraints 재설정
- [x] Cell 초기값 등록 함수 설정
- [x] Cell 활성화 여부 체크 및 ui 변경 로직 적용

**Comment by compuTasha** [comment]
앗 오전에 에이버리에게 전달했어야 했는데 너무 늦었네요,, 죄송합니다 😭

지금 현재 알람만 셀이 활성화되도록 하는 부분은
테이블 단에서 간단하게 처리가 가능해서
수정한 후에 커밋했습니다..! 78d2ebd027d8b12a5db62b71af142b080ca6fac5

셀 기본 색상은 동일하게 두고,
저장된 알람 목록일 경우에는 cell 자체에 opacity를 주는 방식으로 해결했습니다
이렇게 했을 때 셀 배경까지 비활성화된 느낌이 드는 것 같아서 이대로 적용했으면 하는데 어떠신가요?!

<img width="300" alt="image" src="https://user-images.githubusercontent.com/51108729/180838796-502972fd-666b-4080-ad50-821ff54e12b0.png">

**Comment by compuTasha** [comment]
그리고 현재 셀 배경색으로 커스텀 색상이 들어간 것 같은데
editing mode에서 튀어나오는(?) 영역 색상이랑 달라서 
테이블 셀 색상도 디폴트 색상인 `secondarySystemGroupedBackgroundColor` 로 변경했습니다!  dfa53b7f41f6f59ab24f6bd9b5605778ebd6bcc2

<img width="336" alt="image" src="https://user-images.githubusercontent.com/51108729/180840587-2c25f380-0af2-4ebf-9800-3d1682771248.png">
<img width="344" alt="image" src="https://user-images.githubusercontent.com/51108729/180840688-b33578f1-e780-4b10-9e5f-b3abedec93f1.png">

**Comment by chaneeii** [comment]
@compuTasha  아하 ㅠㅠㅠ 이미 어제,,,,,,작업을 다 해버렸는데,,, 진작볼걸그랬네요ㅜㅜㅜ 이걸 다시 커밋을 취소해야하는건지 모르겠어서 우선  PR 남겨봅니다ㅠ
