### ISSUE TITLE
🚚 move : 파일 및 폴더 정리

### ISSUE THREAD

**Issue by compuTasha** [DeveloperAcademy-POSTECH/MC3-Team13-Inception#40]
## 💡 Issue
파일 및 폴더를 정리합니다

## 📝  todo
- [x] sounds 폴더 생성 및 알람 사운드 파일 이동
- [x] manager 폴더 생성 및 core data manager 관련 파일 이동
- [x] Supports 폴더 생성 및 AppDelegate, SceneDelegate, Info.plist 이동
- [x] 메인 스토리보드 및 기존 뷰컨트롤러 삭제
- [x] 런치스크린을 Screens 폴더로 이동
