### ISSUE TITLE
✨ feat : 수면만족도 CoreData 기록 

### ISSUE THREAD

**Issue by chaneeii** [DeveloperAcademy-POSTECH/MC3-Team13-Inception#42]
## 💡 Issue
수면만족도 CoreData 기록 하거나 건너뜁니다.

## 📝  todo
- [x] SleepRecord에 만족도추가하여 CoreData에 추가
- [x] 건너뛰기 혹은 X 버튼을 눌러 SKIP 하기
- [x] Skip 혹은 만족도 추가 후 홈으로 이동

## ref
- root뷰 빼고 모든 뷰 제거하는법 : https://devureak.tistory.com/15
