### ISSUE TITLE
✨ feat : 추천 알람 '추가' 버튼 클릭 시 동작 구현

### ISSUE THREAD

**Issue by taehyeonk** [DeveloperAcademy-POSTECH/MC3-Team13-Inception#45]
## 💡 Issue
- 추천 알람 Cell에서 '추가' 버튼 클릭 시 수행해야 하는 기능 구현
- Alarm 데이터가 Alarm List에 추가되도록 구현
- Notification 설정이 되도록 구현

## 📝  todo
- [x] Alert 내에 '변경하기' 버튼 클릭 시 알람 목록에 현재 알람으로 추가되도록 구현
- [x] 현재 알람으로 세팅되고 나머지 알람들은 isOn=false 되도록 구현
- [x] Notification 구현해 둔 함수 활용해서 알림 설정 구현
