### ISSUE TITLE
✅ add : 알람 목록 뷰 UI Layout 구성

### ISSUE THREAD

**Issue by compuTasha** [DeveloperAcademy-POSTECH/MC3-Team13-Inception#6]
## 💡 Issue
알람 목록 뷰 전체적인 레이아웃을 구성합니다

<img src="https://user-images.githubusercontent.com/51108729/179351175-61e39ca4-f4b6-4a45-8679-8eba874ede55.png"  width="200">

## 📝  todo
- [x] 상단 네비게이션 바 구현
- [x] 현재 알람 테이블뷰 위치하기
- [x] 저장된 알람 테이블뷰 위치하기
- [x] 알람 해지 버튼 구현
- [x] 테이블 편집 버튼 구현
- [x] 커스텀 셀과 연결
