### ISSUE TITLE
 ✅ add : 개인정보처리방침 및 팀원 소개 페이지 추가

### ISSUE THREAD

**Issue by compuTasha** [DeveloperAcademy-POSTECH/MC3-Team13-Inception#73]
## 💡 Issue
알람 추천 페이지에 '설정' 페이지를 추가합니다.

## 📝  todo
- [x] 내비게이션 바 아이템 추가
- [x] 테이블뷰 생성
- [x] 개인정보처리방침 페이지 생성 및 연결
- [x] 팀원 소개 페이지 생성 및 연결
